Rscript granges_to_tagAlign.R /oak/stanford/groups/akundaje/projects/alzheimers_parkinsons/dopa_neurons_cluster_10/DopaNeurons_Cluster10_AllFrags_projSUNI2.rds /oak/stanford/groups/akundaje/projects/alzheimers_parkinsons/dopa_neurons_cluster_10/DopaNeurons_Cluster10_AllFrags_projSUNI2.tagAlign.gz 99 


