#get the narrowPeak, tagAlign, fc bigwig, pval bigwig files generated by the pipeline
prefix=/oak/stanford/groups/akundaje/projects/alzheimers_parkinsons

#narrowPeaks 
#find $prefix  -wholename "*call-reproducibility_overlap/execution/optimal_peak.narrowPeak.gz" | grep -v "glob" | grep -v "duplicate"  &> $prefix/narrowPeak.files.txt

#pooled tagAligns (one tagAlign per biological replicate) 
#find $prefix -wholename "*call-pool_ta/execution/*.nodup.tn5.pooled.tagAlign.gz" | grep -v "glob" | grep -v "duplicate"  &> $prefix/nodup.tn5.pooled.tagAlign.files.txt

#pooled fold change bigwig 
#find $prefix -wholename "*/call-macs2_signal_track_pooled/execution/*nodup.tn5.pooled.fc.signal.bigwig" | grep -v "glob" | grep -v "duplicate" &> $prefix/nodup.tn5.pooled.fc.signal.bigwig 

#pooled pval bigwig 
#find $prefix -wholename "*/call-macs2_signal_track_pooled/execution/*nodup.tn5.pooled.pval.signal.bigwig" | grep -v "glob" | grep -v "duplicate" &> $prefix/nodup.tn5.pooled.pval.signal.bigwig


#if there are multiple entries for a given file, filter by timestamp 
python filter_by_timestamp.py --dir_steps=11 --file_list $prefix/narrowPeak.files.txt --outf $prefix/narrowPeak.files.nodup.txt 
python filter_by_timestamp.py --dir_steps=11 --file_list $prefix/nodup.tn5.pooled.tagAlign.files.txt --outf $prefix/nodup.tn5.pooled.tagAlign.files.nodup.txt 
python filter_by_timestamp.py --dir_steps=11 --file_list $prefix/nodup.tn5.pooled.fc.signal.bigwig --outf $prefix/nodup.tn5.pooled.fc.signal.nodup.bigwig
python filter_by_timestamp.py --dir_steps=11 --file_list $prefix/nodup.tn5.pooled.pval.signal.bigwig --outf $prefix/nodup.tn5.pooled.pval.signal.nodup.bigwig


#get any failed runs 
./get_failed_runs.sh 
