CUDA_VISIBLE_DEVICES=$2 kerasAC_cross_validate --nonzero_bin_path /mnt/lab_data3/soumyak/adpd/deeplearning/inputs/input.max.hdf5 \
		    --universal_negative_path /mnt/lab_data3/soumyak/adpd/deeplearning/inputs/universal_negatives.input.max.hdf5 \
		    --model_hdf5 /mnt/lab_data3/soumyak/adpd/deeplearning/models/regression/max/$1.model.max \
            --architecture_spec regression \
		    --batch_size 256 \
            --num_train 100000 \
            --num_valid 50000 \
		    --train_upsample 0.3 \
		    --tensorboard_logdir logs \
		    --tensorboard \
            --tasks $1 \
		    --num_tasks 1 \
		    --threads 40 \
		    --max_queue_size 1000 \
		    --init_weights /mnt/lab_data3/soumyak/adpd/deeplearning/encode-roadmap.dnase_tf-chip.batch_256.params.npz \
		    --patience 10 \
		    --patience_lr 3 \
            --assembly hg38 \
            --chromsizes /mnt/data/annotations/by_release/hg38/hg38.chrom.sizes \
		    --ref_fasta /mnt/data/annotations/by_release/hg38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta \
		    --performance_metrics_regression_file /mnt/lab_data3/soumyak/adpd/deeplearning/predictions/regression/max/performance/$1.max.perfs \
		    --predictions_pickle /mnt/lab_data3/soumyak/adpd/deeplearning/predictions/regression/max/pickles/$1.max.preds
