CUDA_VISIBLE_DEVICES=$2 kerasAC_cross_validate \
            --data_path /mnt/lab_data3/soumyak/adpd/deeplearning/inputs/microglia.input.hdf5 \
		    --model_hdf5 /mnt/lab_data3/soumyak/adpd/deeplearning/models/regression/single_cell/$1.new.model \
            --architecture_spec regression \
		    --batch_size 300 \
            --num_train 1000000 \
            --num_valid 500000 \
            --upsample_thresh_list 0.0 0.2 0.4 0.6 0.8 1.1 1.4 1.7 2.0 2.4 2.8 3.2 10.0 \
            --upsample_ratio_list 0.17 0.15 0.13 0.11 0.09 0.08 0.07 0.06 0.05 0.04 0.03 0.02 \
            --tasks $1 \
		    --num_tasks 1 \
            --splits $3 \
		    --threads 20 \
		    --init_weights /mnt/lab_data3/soumyak/adpd/deeplearning/encode-roadmap.dnase_tf-chip.batch_256.params.npz \
		    --patience 15 \
		    --patience_lr 2 \
            --assembly hg38 \
            --chromsizes /mnt/data/annotations/by_release/hg38/hg38.chrom.sizes \
		    --ref_fasta /mnt/data/annotations/by_release/hg38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta \
		    --performance_metrics_regression_file /mnt/lab_data3/soumyak/adpd/deeplearning/predictions/regression/single_cell/performance/$1.new.perfs \
		    --predictions_pickle /mnt/lab_data3/soumyak/adpd/deeplearning/predictions/regression/single_cell/pickles/$1.new.preds \
			#--vcf_file $3 \
